# Generated by Django 5.0.3 on 2024-03-06 07:41

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('variable1', backend.models.WeekdayField(choices=[('Friday', 'Friday'), ('Thursday', 'Thursday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Saturday', 'Saturday'), ('Wednesday', 'Wednesday')], max_length=20)),
                ('variable2', backend.models.WeekdayField(choices=[('Thursday', 'Thursday'), ('Saturday', 'Saturday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=20)),
                ('variable3', backend.models.WeekdayField(choices=[('Sunday', 'Sunday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday')], max_length=20)),
            ],
        ),
    ]
