# Generated by Django 5.0.3 on 2024-03-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='variable1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='variable2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='variable3',
            field=models.CharField(max_length=50),
        ),
    ]
