# Generated by Django 5.0.3 on 2024-03-06 07:53

import backend.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_client_variable1_alter_client_variable2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='variable1',
            field=backend.models.WeekdayField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Saturday', 'Saturday'), ('Thursday', 'Thursday'), ('Wednesday', 'Wednesday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=50),
        ),
    ]
