# Generated by Django 5.0.3 on 2024-03-06 07:57

import backend.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_client_variable1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='variable1',
            field=backend.models.WeekdayField(choices=[('Monday', 'Monday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Wednesday', 'Wednesday'), ('Sunday', 'Sunday'), ('Tuesday', 'Tuesday'), ('Thursday', 'Thursday')], max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='variable2',
            field=backend.models.WeekdayField(choices=[('Thursday', 'Thursday'), ('Sunday', 'Sunday'), ('Saturday', 'Saturday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Friday', 'Friday')], max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='variable3',
            field=backend.models.WeekdayField(choices=[('Sunday', 'Sunday'), ('Saturday', 'Saturday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=50),
        ),
    ]
