# Generated by Django 5.0.3 on 2024-03-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_formdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='formdata',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='formdata',
            name='availability',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='formdata',
            name='domain',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='formdata',
            name='preference',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='formdata',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
