# Generated by Django 5.0.3 on 2024-03-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('variable1', models.CharField(max_length=50)),
                ('variable2', models.CharField(max_length=50)),
                ('variable3', models.CharField(max_length=50)),
            ],
        ),
    ]
