# Generated by Django 4.1.7 on 2024-03-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_formdatacompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('variable1', models.CharField(max_length=50)),
                ('variable2', models.CharField(max_length=50)),
                ('variable3', models.CharField(max_length=50)),
            ],
        ),
    ]
